version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "zone.js"
          - "rxjs"
          - "@angular-devkit/*"
          - "@schematics/*"
        update-types:
          - "minor"
          - "patch"
